In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
array = np.array([1, 2, 3, 4, 5])
print(array)

[1 2 3 4 5]


In [3]:
array.dtype

dtype('int64')

In [4]:
array.shape

(5,)

In [5]:
array.ndim

1

In [6]:
array2 = array.reshape(1, 5)
print(array2)

[[1 2 3 4 5]]


In [7]:
a1 = np.arange(1, 10, 2)
a2 = np.linspace(1, 10, 20)
print(a1)
print(a2)

[1 3 5 7 9]
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

In [8]:
## Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. 
# Replace all the elements in the third column with 1.

array = np.random.randint(1,20,size=(5,5))
print(array)
print("\n")
array[:,2] = 1
print(array)

[[19  8 17 11  6]
 [19 11  9  9  8]
 [ 6 17 16  7 10]
 [11  4  6 15  8]
 [ 1  1  7  9 13]]


[[19  8  1 11  6]
 [19 11  1  9  8]
 [ 6 17  1  7 10]
 [11  4  1 15  8]
 [ 1  1  1  9 13]]


In [9]:
## Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

array = np.arange(1,17)
array = array.reshape(4,4)
print(array)
print("\n")
np.fill_diagonal(array, 0)
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

In [10]:
## Create a NumPy array of shape (6, 6) with values from 1 to 36. 
# Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

array = np.arange(1,37)
array = array.reshape(6,6)
print(array)
print("\n")
array2 = array[2:5, 1:4]
print(array2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [11]:
## Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

array = np.random.randint(1, 10, size=(5, 5)) 
print(array)
print("\n")
array2 = array[0 ,:] # top row
array3 = array[-1 ,:] # bottom row
array4 = array[1:4 ,0] # left column
array5 = array[1:4 ,-1] # right column
border_elements = np.concatenate((array2 , array3 , array4 , array5))
print(border_elements)


[[4 3 1 8 8]
 [3 8 3 9 2]
 [6 5 1 7 8]
 [2 6 8 3 7]
 [1 8 2 3 2]]


[4 3 1 8 8 1 8 2 3 2 3 6 2 2 8 7]


In [12]:
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Extract the elements on the border
border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("Border elements:")
print(border_elements)

Original array:
[[ 7  8 10 14 19]
 [ 6 12  9 13 20]
 [ 6 19 18 17  5]
 [18 10  5  8  6]
 [12  9 15  6 17]]
Border elements:
[ 7  8 10 14 19 12  9 15  6 17  6  6 18 20  5  6]


### Assignment 3: Array Operations

In [13]:
## Create two NumPy arrays of shape (3, 4) filled with random integers. 
# Perform element-wise addition, subtraction, multiplication, and division.

array1 = np.random.randint(1, 10, size=(3, 4))
array2 = np.random.randint(1, 10, size=(3, 4))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)
print("\nElement-wise addition:")
print(array1 + array2)
print("\nElement-wise subtraction:")
print(array1 - array2)
print("\nElement-wise multiplication:")
print(array1 * array2)
print("\nElement-wise division:")
print(array1 / array2)

Array 1:
[[5 9 3 8]
 [5 3 8 1]
 [9 5 2 5]]
Array 2:
[[7 3 3 7]
 [3 8 1 1]
 [2 3 9 2]]

Element-wise addition:
[[12 12  6 15]
 [ 8 11  9  2]
 [11  8 11  7]]

Element-wise subtraction:
[[-2  6  0  1]
 [ 2 -5  7  0]
 [ 7  2 -7  3]]

Element-wise multiplication:
[[35 27  9 56]
 [15 24  8  1]
 [18 15 18 10]]

Element-wise division:
[[0.71428571 3.         1.         1.14285714]
 [1.66666667 0.375      8.         1.        ]
 [4.5        1.66666667 0.22222222 2.5       ]]


In [14]:
## Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.
array = np.arange(1, 17)
array = array.reshape(4, 4)
print("Original array:")
print(array)
print("\nRow-wise sum:")
print(np.sum(array, axis=1))
print("\nColumn-wise sum:")
print(np.sum(array, axis=0))

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Row-wise sum:
[10 26 42 58]

Column-wise sum:
[28 32 36 40]


### Assignment 4: Statistical Operations

In [15]:
## Create a NumPy array of shape (5, 5) filled with random integers. 
# Compute the mean, median, standard deviation, and variance of the array.

array = np.random.randint(1, 10, size=(5, 5))
print("Original array:")
print(array)
print("\nMean:")
print(array.mean())
print(np.mean(array))
print("\nMedian:")
print(np.median(array))
print("\nStandard deviation:")
print(np.std(array))
print("\nVariance:")
print(np.var(array))

Original array:
[[7 1 7 7 4]
 [7 8 6 5 4]
 [2 8 4 7 2]
 [5 9 9 8 3]
 [1 2 5 4 5]]

Mean:
5.2
5.2

Median:
5.0

Standard deviation:
2.416609194718914

Variance:
5.839999999999999


In [16]:
## Create a NumPy array of shape (3, 3) with values from 1 to 9. 
# Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

array = np.arange(1, 10).reshape(3, 3)
print("Original array:")
print(array)
mean = np.mean(array)
std = np.std(array)
normalized_array = (array - mean) / std
print("\nNormalized array:")
print(normalized_array)

print("\n")
print("mean of normalized array:")
print(np.mean(normalized_array))
print("std of normalized array:")
print(np.std(normalized_array))

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Normalized array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


mean of normalized array:
0.0
std of normalized array:
1.0


### Assignment 5: Broadcasting

In [17]:
## Create a NumPy array of shape (3, 3) filled with random integers. 
# Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

array2d = np.random.randint(1, 10, size=(3, 3))
print("2D array:")
print(array2d)
array1d = np.array([1, 2, 3])   
print("1D array:")
print(array1d)
result = array2d + array1d
print("\nResult of broadcasting:")
print(result)

2D array:
[[1 1 2]
 [9 3 3]
 [3 7 8]]
1D array:
[1 2 3]

Result of broadcasting:
[[ 2  3  5]
 [10  5  6]
 [ 4  9 11]]


In [18]:
array2d = np.random.randint(1, 10, size=(3, 3))
print("2D array:")
print(array2d)
array1d = np.array([[1, 2, 3]])   
print("1D array:")
print(array1d)
result = array2d + array1d
print("\nResult of broadcasting:")
print(result)

2D array:
[[3 1 2]
 [9 7 8]
 [2 8 4]]
1D array:
[[1 2 3]]

Result of broadcasting:
[[ 4  3  5]
 [10  9 11]
 [ 3 10  7]]


In [19]:
## Create a NumPy array of shape (4, 4) filled with random integers. 
# Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

array2d = np.random.randint(1, 10, size=(4, 4))
print("2D array:")
print(array2d)
array1d = np.array([1, 2, 3, 4])
print("1D array:")
print(array1d)
result1 = array2d - array1d[:, np.newaxis]  # Reshape to (4, 1) for broadcasting   
result2 = array2d - array1d
print("\nResult of broadcasting:")
print(result1,"\n")
print(result2)

2D array:
[[4 1 4 1]
 [6 5 9 4]
 [4 8 9 2]
 [6 8 1 8]]
1D array:
[1 2 3 4]

Result of broadcasting:
[[ 3  0  3  0]
 [ 4  3  7  2]
 [ 1  5  6 -1]
 [ 2  4 -3  4]] 

[[ 3 -1  1 -3]
 [ 5  3  6  0]
 [ 3  6  6 -2]
 [ 5  6 -2  4]]


### Assignment 6: Linear Algebra

In [20]:
## Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original matrix:")
print(array)
det = np.linalg.det(array)
print("\nDeterminant:")
print(det)
try:
    inv = np.linalg.inv(array)
    print("\nInverse:")
    print(inv)
except np.linalg.LinAlgError:
    print("\nMatrix is singular, cannot compute inverse.")

eig_vector = np.linalg.eig(array)
print("\nEigenvalues:")
print(eig_vector)


Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant:
0.0

Matrix is singular, cannot compute inverse.

Eigenvalues:
EigResult(eigenvalues=array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]), eigenvectors=array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))


In [21]:
## Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

array1 = np.random.randint(1, 10, size=(2, 3))
array2 = np.random.randint(1, 10, size=(3, 2))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)
result = np.dot(array1, array2)
print("\nMatrix multiplication result:")
print(result)
print("\n")
print("Matrix multiplication result using @ operator:")
print(array1 @ array2)
# array3 = np.random.randint(1, 10, size=(2, 3))
# print(array1*array3)


Array 1:
[[1 3 7]
 [5 9 3]]
Array 2:
[[5 7]
 [9 2]
 [3 3]]

Matrix multiplication result:
[[ 53  34]
 [115  62]]


Matrix multiplication result using @ operator:
[[ 53  34]
 [115  62]]


In [22]:
np.linalg.inv(result)

array([[-0.09935897,  0.05448718],
       [ 0.18429487, -0.0849359 ]])

### Assignment 7: Advanced Array Manipulation

In [23]:
## Create a NumPy array of shape (3, 3) with values from 1 to 9. 
# Reshape the array to shape (1, 9) and then to shape (9, 1).

array = np.arange(1, 10).reshape(3, 3)
print("Original array:")
print(array)
reshaped_array1 = array.reshape(1, 9)
print("\nReshaped array (1, 9):")
print(reshaped_array1)
reshaped_array2 = array.reshape(9,1)
print("\nReshaped array (9, 1):")
print(reshaped_array2)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reshaped array (1, 9):
[[1 2 3 4 5 6 7 8 9]]

Reshaped array (9, 1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [24]:
## Create a NumPy array of shape (5, 5) filled with random integers. 
# Flatten the array and then reshape it back to (5, 5).

array = np.random.randint(1, 10, size=(5, 5))
print("Original array:")
print(array)
flattened_array = array.flatten()  # Flatten the array(1D)
print("\nFlattened array:")
print(flattened_array)
reshaped_array = flattened_array.reshape(5, 5)
print("\nReshaped array:")
print(reshaped_array)

Original array:
[[8 1 1 5 5]
 [8 6 9 2 2]
 [9 5 4 5 6]
 [7 2 4 2 8]
 [1 3 5 1 3]]

Flattened array:
[8 1 1 5 5 8 6 9 2 2 9 5 4 5 6 7 2 4 2 8 1 3 5 1 3]

Reshaped array:
[[8 1 1 5 5]
 [8 6 9 2 2]
 [9 5 4 5 6]
 [7 2 4 2 8]
 [1 3 5 1 3]]


### Assignment 8: Fancy Indexing and Boolean Indexing

In [25]:
## Create a NumPy array of shape (5, 5) filled with random integers. 
# Use fancy indexing to extract the elements at the corners of the array.

array = np.random.randint(1, 10, size=(5, 5))
print("Original array:")
print(array)

corners = array[[0, 0, -1, -1],[0, -1, 0, -1]]  # row indices and column indices
print("\nCorner elements:")
print(corners)

Original array:
[[1 7 3 5 2]
 [3 7 8 2 2]
 [2 3 5 5 4]
 [4 5 7 4 7]
 [2 7 8 3 6]]

Corner elements:
[1 2 2 6]


In [26]:
## Create a NumPy array of shape (4, 4) filled with random integers. 
# Use boolean indexing to set all elements greater than 10 to 10.

array = np.random.randint(1, 20, size=(4, 4))   
print("Original array:")
print(array)
array[array > 10] = 10
print("\nModified array:")
print(array)

Original array:
[[16  5  3 17]
 [ 7  6 12  1]
 [ 2 15  8 12]
 [13 11 10 15]]

Modified array:
[[10  5  3 10]
 [ 7  6 10  1]
 [ 2 10  8 10]
 [10 10 10 10]]


In [27]:
array = np.random.randint(1, 20, size=(4, 4))   
print("Original array:")
print(array)
array = np.where(array > 10, array, 10)  # Set all elements greater than 10 to 10
print("Where condition:")
print("\nModified array:")
print(array)

Original array:
[[17 13 19 14]
 [19 11 14 16]
 [ 8 18 18  7]
 [ 3 11 14  6]]
Where condition:

Modified array:
[[17 13 19 14]
 [19 11 14 16]
 [10 18 18 10]
 [10 11 14 10]]


### Assignment 9: Structured Arrays

In [28]:
## reate a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). 
# Add some data and sort the array by age.

dtype = np.dtype([('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
array = np.array([('Alice', 25, 55.5), ('Bob', 30, 70.2), ('Charlie', 22, 60.1)], dtype=dtype)
print("Structured array:")
print(array)

Structured array:
[('Alice', 25, 55.5) ('Bob', 30, 70.2) ('Charlie', 22, 60.1)]


In [29]:
## Create a structured array with fields 'x' and 'y' (both integers). 
# Add some data and compute the Euclidean distance between each pair of points.

dtype = np.dtype([('x', 'i4'), ('y', 'i4')])
array = np.array([(1, 2), (3, 4), (5, 6)], dtype=dtype)
print("Structured array:")
print(array)

Structured array:
[(1, 2) (3, 4) (5, 6)]


In [30]:
array[0][0]

np.int32(1)

In [31]:
array.dtype

dtype([('x', '<i4'), ('y', '<i4')])

In [32]:
result.dtype

dtype('int32')

### Assignment 10: Masked Arrays

In [33]:
## Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. 
# Compute the sum of the unmasked elements.

array = np.random.randint(1, 20, size=(4, 4))
print("Original array:")
print(array)

masked_array = np.ma.masked_where(array > 10, array)
print("\nMasked array:")
print(masked_array)
print("\nUnmasked elements:")
print(masked_array.compressed())
print("\nSum of unmasked elements:")
print(masked_array.sum())

Original array:
[[16 11  9 17]
 [ 1 14  8 11]
 [11  2  3  2]
 [ 8 14 15  4]]

Masked array:
[[-- -- 9 --]
 [1 -- 8 --]
 [-- 2 3 2]
 [8 -- -- 4]]

Unmasked elements:
[9 1 8 2 3 2 8 4]

Sum of unmasked elements:
37


In [34]:
array = np.random.randint(1, 20, size=(4, 4))
print("Original array:")
print(array)

masked_array = np.where(array > 10, array, np.ma.masked)
print("\nMasked array:")
print(masked_array)
print("\nUnmasked elements:")
print(masked_array)
print("\nSum of unmasked elements:")
print(masked_array.sum())

Original array:
[[13  2 19 12]
 [ 8 15 15  5]
 [ 2  3  9  7]
 [ 3 13 17 10]]

Masked array:
[[13.  0. 19. 12.]
 [ 0. 15. 15.  0.]
 [ 0.  0.  0.  0.]
 [ 0. 13. 17.  0.]]

Unmasked elements:
[[13.  0. 19. 12.]
 [ 0. 15. 15.  0.]
 [ 0.  0.  0.  0.]
 [ 0. 13. 17.  0.]]

Sum of unmasked elements:
104.0


In [35]:
## Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. 
# Replace the masked elements with the mean of the unmasked elements.

array = np.random.randint(1, 20, size=(3, 3))
print("Original array:")
print(array)

masked_array = np.ma.masked_array(array,mask=np.eye(3, dtype=bool))  # mask diagonal elements
print("\nMasked array:")    
print(masked_array)
mean_value = masked_array.mean()   # mean of unmasked elements
print("\nMean of unmasked elements:")
print(mean_value)
masked_array = np.ma.filled(masked_array, mean_value)  # fill masked elements with mean value
print("\nMasked array with mean value:")
print(masked_array)


Original array:
[[10 11 13]
 [16  5  2]
 [ 4 18  1]]

Masked array:
[[-- 11 13]
 [16 -- 2]
 [4 18 --]]

Mean of unmasked elements:
10.666666666666666

Masked array with mean value:
[[10 11 13]
 [16 10  2]
 [ 4 18 10]]


In [36]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original array:")
print(array)
print("Sin :", np.sin(array))
print("Cos :", np.cos(array))
print("Tan :", np.tan(array))
print("Exp :", np.exp(array))
print("Log :", np.log(array))
print("Sqrt :", np.sqrt(array))
print("Abs :", np.abs(array))
print("Floor :", np.floor(array))

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sin : [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
Cos : [[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]
Tan : [[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]
Exp : [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
Log : [[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]
Sqrt : [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
Abs : [[1 2 3]
 [4 5 6]
 [7 8 9]]
Floor : [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
